server:
  port: 8080
spring:
  cache:
    redis:
      time-to-live: 180000
  application:
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://49.232.166.172:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: Test!234
  redis:
    host: 49.232.166.172
    port: 6379
    password: 'Test!234'
    database: 1
#    host: 127.0.0.1
#    port: 6379
#    password: 123
#    database: 0
    jedis:
      # Redis连接池，是基于jedis的
      pool:
        max-active: 8 # 最大连接池
        max-wait: 5 # 阻塞时间ms
        max-idle: 4 # 连接池中最大空闲
        min-idle: 0 # 连接池中最小空闲
#    timeout: 5000000


mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

reggie:
  path: \root\java\uploadImage\